context:
  name: beckhoff-ads
  version: v22

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/Beckhoff/ADS/archive/refs/tags/${{ version }}.tar.gz
  sha256: 7330e032a7add1f97df6759cc1610c06760ae928ecfa4531915a3595ab70aaaf
  patches: 
    # meson.build on v22 does not provide install directives - add them via patch. To be checked for newer versions.
    - meson-build.patch

build:
  number: 0
  skip:
    - win
  script: |
    meson setup build --prefix="$PREFIX" -Dlibdir="$PREFIX/lib" -Dwerror=false
    ninja -C build install

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - meson
    - ninja

tests:
  - script:
      - test -d "${PREFIX}/include/AdsLib"
      - test -f "${PREFIX}/include/AdsLib/AdsLib.h"
      - test -f "${PREFIX}/bin/adstool"

about:
  homepage: https://github.com/Beckhoff/ADS
  license: MIT
  license_file: LICENSE
  summary: Beckhoff protocol to communicate with TwinCAT devices
  description: | 
        This library is intended to provide easy use as ADS client applications running on non-windows systems 
        (e.g. FreeBSD, Linux, ...) to communicate with TwinCAT devices via TCP/IP.
  documentation: https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_ads_intro/index.html
  repository: https://github.com/Beckhoff/ADS

extra:
  recipe-maintainers:
    - AndreFavotto
    - mac-kan
    - javicereijo
