
{% set name = "cerberecontrib-ghrsst" %}
{% set version = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/cerbere/cerberecontrib-ghrsst/-/archive/{{ version }}/cerberecontrib-ghrsst-{{ version }}.tar.gz
  sha256: 7f84aeb91bb181c20b2ebe9f9405407d0f4717a187e66f4366eb4ad49cd970c3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.11
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >=3.10.0,<3.11
    - cerbere >=3.1.2

test:
  imports:
    - cerberecontrib_ghrsst
  requires:
    - cerbere
    - cerberecontrib_ghrsst
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Cerbere reader for any GHRSST product.
  license: LGPL-3.0-only
  license_file: LICENSE.md
  home: https://gitlab.ifremer.fr/cerbere/cerberecontrib-ghrsst
  doc_url: https://cerbere.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - cso2943
    - criou-cg
    - erwanbodere
    - jfpiolle
    - Marie59
